version: "3.3"

services:
  anything-llm:
    image: mintplexlabs/anythingllm:${SOFTWARE_VERSION_TAG}
    restart: always
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./docker.env:/app/server/.env"
      - "./storage:/app/server/storage"
    ports:
      - "172.17.0.1:52840:3001"
    env_file:
      - .env

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/storage
      o: bind
